name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run linter
      run: vendor/bin/phpcs --standard=phpcs.xml --report=checkstyle src/ -n

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: 4d8c6ef25170af09344e8a0c5adfd35c62774a27 
        SONAR_HOST_URL: https://sonarcloud.io  

    - name: Run tests
      env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          IMPERSONATED_USER_ID: ${{ secrets.IMPERSONATED_USER_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SIGNER_EMAIL: ${{ secrets.SIGNER_EMAIL }}
          SIGNER_NAME: ${{ secrets.SIGNER_NAME }}
      run: composer run-script test
